INSERT INTO IMPORTACAO
SELECT
	DI::INTEGER,
	TRIM(UF_DESPACHO),
	CASE WHEN TRIM(UF_CONSIGNATARIO) = '-1' THEN NULL ELSE TRIM(UF_CONSIGNATARIO) END,
	CNPJ_IMPORTADOR::BIGINT::CHAR(14),
	UF_IMPORTADOR,
	CASE WHEN TRIM(CNPJ_ADQUIRENTE) = '-1' THEN NULL ELSE CNPJ_ADQUIRENTE::BIGINT::CHAR(14) END,
	DESEMBARACO::DATE,
	DESC_DECLARACAO,
	TIPO_CONHECIMENTO,
	TIPO_GUIA_RECOLHIMENTO,
	REGEXP_REPLACE(CIF, ',', '.')::NUMERIC(10,2),
	REGEXP_REPLACE(BC_ICMS, ',', '.')::NUMERIC(10,2),
	REGEXP_REPLACE(ICMS_RECOLHIDO, ',', '.')::NUMERIC(10,2),
	REGEXP_REPLACE(ICMS_ESTIMADO, ',', '.')::NUMERIC(10,2)
FROM DI_TEMP;

INSERT INTO IMPORTACAO_ADICAO
SELECT
	DI::INTEGER,
	ADICAO::INTEGER,
	JUSTIFICATIVA_TRIBUT,
	FUNDAMENTACAO,
	REGIME_TRIB_II,
	NCM::INTEGER,
	REGEXP_REPLACE(BC_II, ',', '.')::NUMERIC(10,2),
	REGEXP_REPLACE(II, ',', '.')::NUMERIC(10,2),
	REGEXP_REPLACE(IPI, ',', '.')::NUMERIC(10,2),
	REGEXP_REPLACE(PIS, ',', '.')::NUMERIC(10,2),
	REGEXP_REPLACE(COFINS, ',', '.')::NUMERIC(10,2),
	REGEXP_REPLACE(OUTRAS_DESPESAS, ',', '.')::NUMERIC(10,2),
	REGEXP_REPLACE(BC_ICMS_ESTIMADO, ',', '.')::NUMERIC(10,2),
	REGEXP_REPLACE(ICMS_ALIQUOTA, ',', '.')::NUMERIC(10,2),
	REGEXP_REPLACE(ICMS_ESTIMADO, ',', '.')::NUMERIC(10,2)
FROM DI_ADICAO_TEMP;