INSERT INTO SUFRAMA
SELECT 
	CHAVE,
	INSCRICAO,
	UF_DEST,
	MUNICIPIO_DEST,
	TIPO_ZONA,
	EVENTO_INTERN,
	DATA_INTERN::DATE,
	EVENTO_VISTORIA,
	DATA_VISTORIA::DATE,
	INGRESSO_SUFRAMA,
	DATA_INGRESSO::DATE
FROM SUFRAMA_TEMP;