INSERT INTO IMPORTACAO
SELECT
	DI::INTEGER,
	UF_DESPACHO,
	UF_CONSIGNATARIO,
	CNPJ_IMPORTADOR::BIGINT::CHAR(14),
	UF_IMPORTADOR,
	CNPJ_ADQUIRENTE::BIGINT::CHAR(14),
	DESEMBARACO::DATE,
	DESC_DECLARACAO,
	TIPO_CONHECIMENTO,
	TIPO_GUIA_RECOLHIMENTO,
	REGEX_REPLACE(CIF, ',', '.')::NUMERIC(10,2),
	REGEX_REPLACE(BC_ICMS, ',', '.')::NUMERIC(10,2),
	REGEX_REPLACE(ICMS_RECOLHIDO, ',', '.')::NUMERIC(10,2),
	REGEX_REPLACE(ICMS_ESTIMADO, ',', '.')::NUMERIC(10,2)
FROM DI_TEMP;

INSERT INTO IMPORTACAO_ADICAO
SELECT
	DI::INTEGER,
	ADICAO::INTEGER,
	JUSTIFICATIVA_TRIBUT,
	FUNDAMENTACAO,
	REGIME_TRIB_II,
	NCM::INTEGER,
	REGEX_REPLACE(BC_II, ',', '.')::NUMERIC(10,2),
	REGEX_REPLACE(II, ',', '.')::NUMERIC(10,2),
	REGEX_REPLACE(IPI, ',', '.')::NUMERIC(10,2),
	REGEX_REPLACE(PIS, ',', '.')::NUMERIC(10,2),
	REGEX_REPLACE(COFINS, ',', '.')::NUMERIC(10,2),
	REGEX_REPLACE(OUTRAS_DESPESAS, ',', '.')::NUMERIC(10,2),
	REGEX_REPLACE(BC_ICMS_ESTIMADO, ',', '.')::NUMERIC(10,2),
	REGEX_REPLACE(ICMS_ALIQUOTA, ',', '.')::NUMERIC(10,2),
	REGEX_REPLACE(ICMS_ESTIMADO, ',', '.')::NUMERIC(10,2)
FROM DI_ADICAO_TEMP;