INSERT INTO CTE
SELECT DISTINCT
   Chave,
   CAST(Numero AS INTEGER),
   CAST(Serie AS INTEGER),
   CAST(Emissao AS DATE),
   Razao_Social_Emit,
   REGEXP_REPLACE(CNPJ_Emit, '[^0-9]+', '', 'g'),
   CASE WHEN LENGTH(TRIM(REGEXP_REPLACE(IE_Emit, '[^0-9]+', '', 'g'))) = 0 THEN NULL ELSE CAST(REGEXP_REPLACE(IE_Emit, '[^0-9]+', '', 'g') AS BIGINT) END,
   UF_Emit,
   Razao_Social_Tom,
   CASE WHEN LENGTH(TRIM(REGEXP_REPLACE(CNPJ_Tom, '[^0-9]+', '', 'g'))) = 0 THEN NULL ELSE REGEXP_REPLACE(CNPJ_Tom, '[^0-9]+', '', 'g') END,
   CASE WHEN LENGTH(TRIM(REGEXP_REPLACE(IE_Tom, '[^0-9]+', '', 'g'))) = 0 THEN NULL ELSE CAST(REGEXP_REPLACE(IE_Tom, '[^0-9]+', '', 'g') AS BIGINT) END,
   UF_Tom,
   Razao_Social_Remet,
   CASE WHEN length(trim(REGEXP_REPLACE(CNPJ_Remet, '[^0-9]+', '', 'g'))) = 0 THEN NULL ELSE REGEXP_REPLACE(CNPJ_Remet, '[^0-9]+', '', 'g') END,
   UF_Remet,
   Razao_Social_Dest,
   CASE WHEN length(trim(REGEXP_REPLACE(CNPJ_Dest, '[^0-9]+', '', 'g'))) = 0 THEN NULL ELSE REGEXP_REPLACE(CNPJ_Dest, '[^0-9]+', '', 'g') END,
   UF_Dest,
   CASE WHEN length(trim(REGEXP_REPLACE(CNPJ_Exped, '[^0-9]+', '', 'g'))) = 0 THEN NULL ELSE REGEXP_REPLACE(CNPJ_Exped, '[^0-9]+', '', 'g') END,
   UF_Exped,
   CASE WHEN length(trim(REGEXP_REPLACE(CNPJ_Receb, '[^0-9]+', '', 'g'))) = 0 THEN NULL ELSE REGEXP_REPLACE(CNPJ_Receb, '[^0-9]+', '', 'g') END,
   UF_Receb,
   Tipo_Doc_Fiscal,
   Natureza_Operacao,
   Descr_Modal,
   Descr_Servico,
   Municipio_Ini,
   UF_Ini,
   Municipio_Fim,
   UF_Fim,
   CFOP::INTEGER,
   Descr_CST,
   REPLACE(REPLACE(Total_CTe, '.', ''), ',', '.') :: NUMERIC(10,2),
   CASE WHEN LENGTH(TRIM(REGEXP_REPLACE(Total_Creditos, '[^0-9]+', '', 'g'))) = 0 THEN 0.0 ELSE REPLACE(REPLACE(Total_Creditos, '.', ''), ',', '.') :: NUMERIC(10,2) END,
   CASE WHEN LENGTH(TRIM(REGEXP_REPLACE(ICMS_BC, '[^0-9]+', '', 'g'))) = 0 THEN 0.0 ELSE REPLACE(REPLACE(ICMS_BC, '.', ''), ',', '.') :: NUMERIC(10,2) END,
   CASE WHEN LENGTH(TRIM(REGEXP_REPLACE(ICMS_Aliquota, '[^0-9]+', '', 'g'))) = 0 THEN 0.0 ELSE REPLACE(REPLACE(ICMS_Aliquota, '.', ''), ',', '.') :: NUMERIC(10,2) END, 
   CASE WHEN LENGTH(TRIM(REGEXP_REPLACE(ICMS_BC_Percentual_Red, '[^0-9]+', '', 'g'))) = 0 THEN 0.0 ELSE REPLACE(REPLACE(ICMS_BC_Percentual_Red, '.', ''), ',', '.') :: NUMERIC(10,2) END,
   CASE WHEN LENGTH(TRIM(REGEXP_REPLACE(ICMS, '[^0-9]+', '', 'g'))) = 0 THEN 0.0 ELSE REPLACE(REPLACE(ICMS, '.', ''), ',', '.') :: NUMERIC(10,2) END,
   CASE WHEN LENGTH(TRIM(REGEXP_REPLACE(ICMSST_BC_Retido_Op_Anterior, '[^0-9]+', '', 'g'))) = 0 THEN 0.0 ELSE REPLACE(REPLACE(ICMSST_BC_Retido_Op_Anterior, '.', ''), ',', '.') :: NUMERIC(10,2) END,
   CASE WHEN LENGTH(TRIM(REGEXP_REPLACE(ICMSST_Retido_Op_Anterior, '[^0-9]+', '', 'g'))) = 0 THEN 0.0 ELSE REPLACE(REPLACE(ICMSST_Retido_Op_Anterior, '.', ''), ',', '.') :: NUMERIC(10,2) END,
   CASE WHEN LENGTH(TRIM(REGEXP_REPLACE(ICMS_Outras_UFs, '[^0-9]+', '', 'g'))) = 0 THEN 0.0 ELSE REPLACE(REPLACE(ICMS_Outras_UFs, '.', ''), ',', '.') :: NUMERIC(10,2) END,
   Indicador_Tom_Serv,
   Indicador_SN,
   NULL,
   0,
   NULL,
   NULL,
   NULL,
   0,
   Situacao_Documento::INTEGER,
   NULL,
   NULL,
   NULL
FROM cte_temp
ON CONFLICT DO NOTHING;