INSERT INTO redf
select
	CNPJ,
	CAST(IE AS BIGINT),
	ECF_SERIE,
	ECF_FABR,
	ECF_MODELO,
	CAST(EMISSAO AS DATE),
	CAST(coo as INTEGER),
	REGEXP_REPLACE(VALOR, ',', '.','gi') :: NUMERIC(8,2)
FROM redf_TEMP;