CREATE TABLE IF NOT EXISTS sat_cupom_item (
	ie 		bigint		not null,
	emissao		date 		not null,
	cancelado	char(1),
	cupom		varchar(50)	not null,
	sat_serie	integer		not null,
	item		integer		not null,
	cod_produto	varchar,
	gtin		bigint,
	desc_produto	varchar,
	ncm		integer		REFERENCES NCM(CODIGO),
	cfop		integer		REFERENCES CFOP(CODIGO),
	unidade		varchar(5),
	quantidade	numeric(10,2),
	regra		varchar,
	valor_unitario	numeric(10,2),
	valor_produtos	numeric(10,2),
	valor_desconto	numeric(10,2),
	valor_outro	numeric(10,2),
	valor_item	numeric(10,2),
	valor_rat_desc	numeric(10,2),
	valor_rat_acr	numeric(10,2),
	origem		varchar,
	cst		varchar,
	icms_aliquota	numeric(10,2),
	icms		numeric(10,2),
	pis_cst		varchar,
	pis_bc		numeric(10,2),
	pis_aliquota	numeric(10,2),
	pis		numeric(10,2),
	pis_vendida	numeric(10,2),
	pis_aliquota_vl	numeric(10,2),
	pis_st_bc	numeric(10,2),
	pis_st_aliquota	numeric(10,2),
	pis_st_vendida	numeric(10,2),
	pis_st_aliquota_vl	numeric(10,2),
	pis_st			numeric(10,2),
	cofins_cst		varchar,
	cofins_bc		numeric(10,2),
	cofins_aliquota		integer,
	cofins			numeric(10,2),
	cofins_vendida		numeric(10,2),
	cofins_aliquota_vl	numeric(10,2),
	cofins_st_bc		numeric(10,2),
	cofins_st_aliquota	numeric(10,2),
	cofins_st_vendida	numeric(10,2),
	cofins_st_aliquota_vl	numeric(10,2),
	cofins_st		numeric(10,2),
	info_adicionais		varchar,
	descricao		varchar,
	descricao_texto		varchar,	
	PRIMARY KEY (ie, cupom, item),
	FOREIGN KEY (ie, cupom) REFERENCES sat_cupom (ie, cupom)
);
CREATE INDEX IF NOT EXISTS sat_cupom_item_ie on SAT_CUPOM_ITEM USING HASH(IE);


CREATE TEMP TABLE sat_cupom_item_temp (
	ie 		VARCHAR,
	emissao		VARCHAR,
	cancelado	VARCHAR,
	cupom		VARCHAR,
	sat_serie	VARCHAR,
	item		VARCHAR,
	cod_produto	VARCHAR,
	gtin		VARCHAR,
	desc_produto	VARCHAR,
	ncm		VARCHAR,
	cfop		VARCHAR,
	unidade		VARCHAR,
	quantidade	VARCHAR,
	regra		VARCHAR,
	valor_unitario	VARCHAR,
	valor_produtos	VARCHAR,
	valor_desconto	VARCHAR,
	valor_outro	VARCHAR,
	valor_item	VARCHAR,
	valor_rat_desc	VARCHAR,
	valor_rat_acr	VARCHAR,
	origem		VARCHAR,
	cst		VARCHAR,
	icms_aliquota	VARCHAR,
	icms		VARCHAR,
	pis_cst		VARCHAR,
	pis_bc		VARCHAR,
	pis_aliquota	VARCHAR,
	pis		VARCHAR,
	pis_vendida	VARCHAR,
	pis_aliquota_vl	VARCHAR,
	pis_st_bc	VARCHAR,
	pis_st_aliquota	VARCHAR,
	pis_st_vendida	VARCHAR,
	pis_st_aliquota_vl	VARCHAR,
	pis_st			VARCHAR,
	cofins_cst		VARCHAR,
	cofins_bc		VARCHAR,
	cofins_aliquota		VARCHAR,
	cofins			VARCHAR,
	cofins_vendida		VARCHAR,
	cofins_aliquota_vl	VARCHAR,
	cofins_st_bc		VARCHAR,
	cofins_st_aliquota	VARCHAR,
	cofins_st_vendida	VARCHAR,
	cofins_st_aliquota_vl	VARCHAR,
	cofins_st		VARCHAR,
	info_adicionais		VARCHAR,
	descricao		VARCHAR,
	descricao_texto		VARCHAR,
	num_cupom		VARCHAR
);