INSERT INTO SAT_CUPOM
SELECT
	CAST(IE AS BIGINT),
	CAST(SAT_SERIE AS INTEGER),
	CAST(EMISSAO AS DATE),
	CANCELADO,
	SUBSTRING(CUPOM, 4),
	CAST(NUMERO AS INTEGER),
	EMISSAO_HORA,
	CAST(RECEPCAO AS DATE),
	REGEXP_REPLACE(VALOR, ',', '.') :: numeric(10,2),
	REGEXP_REPLACE(ICMS, ',', '.') :: numeric(10,2),
	REGEXP_REPLACE(VALOR_PRODUTOS, ',', '.') :: numeric(10,2),
	REGEXP_REPLACE(VALOR_DESCONTO, ',', '.') :: numeric(10,2),
	REGEXP_REPLACE(PIS, ',', '.') :: numeric(10,2),
	REGEXP_REPLACE(COFINS, ',', '.') :: numeric(10,2),
	REGEXP_REPLACE(PIS_ST, ',', '.') :: numeric(10,2),
	REGEXP_REPLACE(COFINS_ST, ',', '.') :: numeric(10,2),
	REGEXP_REPLACE(VALOR_OUTROS, ',', '.') :: numeric(10,2),
	CASE WHEN LENGTH(ACRES_DESCONTO) = 0 THEN 0.0 ELSE REGEXP_REPLACE(ACRES_DESCONTO, ',', '.') :: numeric(10,2) END,
	CASE WHEN LENGTH(TRIBUTOS_ESTIM) = 0 THEN 0.0 ELSE REGEXP_REPLACE(TRIBUTOS_ESTIM, ',', '.') :: numeric(10,2) END
FROM SAT_CUPOM_TEMP;