INSERT INTO INTERMEDIARIO_ARQUIVO
SELECT 
	ID_ARQUIVO::INTEGER,
	CNPJ::BIGINT::CHAR(14),
	REFERENCIA,
	NOME,
	TRANSMISSAO::TIMESTAMP,
	ATIVO::BOOLEAN,
	TRIM(ARQUIVO)
FROM INTERMEDIARIO_ARQUIVO_TEMP;

INSERT INTO INTERMEDIARIO_TRANSACAO
SELECT 
	CNPJ_CLIENTE::BIGINT::CHAR(14),
	EMISSAO::DATE,
	TRANSACAO,
	regexp_replace(VALOR, ',', '.')::NUMERIC(10,2),
	ID_ARQUIVO::INTEGER,
	qtd::integer,
	'IC'
FROM INTERMEDIARIO_IC_TEMP
ON CONFLICT DO NOTHING;

INSERT INTO INTERMEDIARIO_TRANSACAO
SELECT 
	CNPJ_CLIENTE::BIGINT::CHAR(14),
	EMISSAO::DATE,
	TRANSACAO,
	regexp_replace(VALOR, ',', '.')::NUMERIC(10,2),
	ID_ARQUIVO::INTEGER,
	qtd::integer,
	'IF'
FROM INTERMEDIARIO_IC_TEMP
ON CONFLICT DO NOTHING;