CREATE TABLE IF NOT EXISTS cfop (
	codigo int4 NOT NULL,
	descricao varchar NULL,
	nfe bool NULL,
	comunica bool NULL,
	transp bool NULL,
	devol bool NULL,
	rba bool NULL,
	CONSTRAINT cfop_pkey PRIMARY KEY (codigo)
);

INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (1911,'Entrada de amostra grátis',true,false,false,false,false),
	 (2918,'Devolução de mercadoria remetida em consignação mercantil ou industrial',true,false,false,true,true),
	 (3201,'Devolução de venda de produção do estabelecimento',true,false,false,true,true),
	 (3202,'Devolução de venda de mercadoria adquirida ou recebida de terceiros',true,false,false,true,true),
	 (3205,'Anulação de valor relativo à prestação de serviço de comunicação',true,false,false,false,true),
	 (3206,'Anulação de valor relativo à prestação de serviço de transporte',true,false,false,false,true),
	 (3207,'Anulação de valor relativo à venda de energia elétrica',true,false,false,false,true),
	 (3211,'Devolução de venda de produção do estabelecimento sob o regime de drawback ',true,false,false,true,true),
	 (5354,'Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação',false,false,true,false,true),
	 (5911,'Remessa de amostra grátis',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (5101,'Venda de produção do estabelecimento',true,false,false,false,true),
	 (5102,'Venda de mercadoria adquirida ou recebida de terceiros',true,false,false,false,true),
	 (5103,'Venda de produção do estabelecimento efetuada fora do estabelecimento',true,false,false,false,true),
	 (5104,'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento',true,false,false,false,true),
	 (5105,'Venda de produção do estabelecimento que não deva por ele transitar',true,false,false,false,true),
	 (5106,'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar ',true,false,false,false,true),
	 (5109,'Venda de produção do estabelecimento destinada à ZFM ou ALC',true,false,false,false,true),
	 (5110,'Venda de mercadoria, adquirida ou recebida de terceiros, destinada à ZFM ou ALC',true,false,false,false,true),
	 (5116,'Venda de produção do estabelecimento originada de encomenda p/ entrega futura',true,false,false,false,true),
	 (5117,'Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda p/ entrega futura',true,false,false,false,true) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (5118,'Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem',true,false,false,false,true),
	 (5119,'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem',true,false,false,false,true),
	 (1201,'Devolução de venda de produção do estabelecimento ',true,false,false,true,true),
	 (1202,'Devolução de venda de mercadoria adquirida ou recebida de terceiros',true,false,false,true,true),
	 (1203,'Devolução de venda de produção do estabelecimento, destinada à ZFM ou ALC',true,false,false,true,true),
	 (1204,'Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à ZFM ou ALC',true,false,false,true,true),
	 (1205,'Anulação de valor relativo à prestação de serviço de comunicação',true,false,false,false,true),
	 (1206,'Anulação de valor relativo à prestação de serviço de transporte',true,false,false,false,true),
	 (1207,'Anulação de valor relativo à venda de energia elétrica',true,false,false,false,true),
	 (1410,'Devolução de venda de mercadoria, de produção do estabelecimento, sujeita a ST',true,false,false,true,true) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (1411,'Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita a ST',true,false,false,true,true),
	 (1503,'Entrada decorrente de devolução de produto, de fabricação do estabelecimento, remetido com fim específico de exportação',true,false,false,true,true),
	 (1504,'Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros',true,false,false,true,true),
	 (1660,'Devolução de venda de combustível ou lubrificante destinados à industrialização subseqüente',true,false,false,true,true),
	 (1661,'Devolução de venda de combustível ou lubrificante destinados à comercialização',true,false,false,true,true),
	 (1662,'Devolução de venda de combustível ou lubrificante destinados a consumidor ou usuário final',true,false,false,true,true),
	 (1918,'Devolução de mercadoria remetida em consignação mercantil ou industrial',true,false,false,true,true),
	 (2201,'Devolução de venda de produção do estabelecimento',true,false,false,true,true),
	 (2202,'Devolução de venda de mercadoria adquirida ou recebida de terceiros',true,false,false,true,true),
	 (2203,'Devolução de venda de produção do estabelecimento destinada à ZFM ou ALC',true,false,false,true,true) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (2204,'Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à ZFM ou ALC',true,false,false,true,true),
	 (2205,'Anulação de valor relativo à prestação de serviço de comunicação',true,false,false,false,true),
	 (2206,'Anulação de valor relativo à prestação de serviço de transporte',true,false,false,false,true),
	 (2207,'Anulação de valor relativo à venda de energia elétrica',true,false,false,false,true),
	 (2208,'Devolução de produção do estabelecimento, remetida em transferência.',true,false,false,true,true),
	 (2209,'Devolução de mercadoria adquirida ou recebida de terceiros e remetida em transferência',true,false,false,true,true),
	 (2410,'Devolução de venda de produção do estabelecimento, quando o produto sujeito a ST',true,false,false,true,true),
	 (6356,'Prestação de serviço de transporte a estabelecimento de produtor rural',false,false,true,false,true),
	 (2411,'Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita a ST',true,false,false,true,true),
	 (2503,'Entrada decorrente de devolução de produto industrializado pelo estabelecimento, remetido com fim específico de exportação',true,false,false,true,true) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (2504,'Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros',true,false,false,true,true),
	 (2660,'Devolução de venda de combustível ou lubrificante destinados à industrialização subseqüente',true,false,false,true,true),
	 (2661,'Devolução de venda de combustível ou lubrificante destinados à comercialização',true,false,false,true,true),
	 (2662,'Devolução de venda de combustível ou lubrificante destinados a consumidor ou usuário final',true,false,false,true,true),
	 (3503,'Devolução de mercadoria exportada que tenha sido recebida com fim específico de exportação',true,false,false,true,true),
	 (5120,'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem',true,false,false,false,true),
	 (5122,'Venda de produção do estabelecimento remetida p/ industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente',true,false,false,false,true),
	 (5123,'Venda de mercadoria adquirida ou recebida de terceiros remetida p/ industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente',true,false,false,false,true),
	 (5124,'Industrialização efetuada p/ outra empresa',true,false,false,false,true),
	 (5125,'Industrialização efetuada p/ outra empresa quando a mercadoria recebida p/ utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria',true,false,false,false,true) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (5251,'Venda de energia elétrica p/ distribuição ou comercialização',true,false,false,false,true),
	 (5252,'Venda de energia elétrica p/ estabelecimento industrial',true,false,false,false,true),
	 (5253,'Venda de energia elétrica p/ estabelecimento comercial',true,false,false,false,true),
	 (5254,'Venda de energia elétrica p/ estabelecimento prestador de serviço de transporte',true,false,false,false,true),
	 (5255,'Venda de energia elétrica p/ estabelecimento prestador de serviço de comunicação',true,false,false,false,true),
	 (5256,'Venda de energia elétrica p/ estabelecimento de produtor rural',true,false,false,false,true),
	 (5257,'Venda de energia elétrica p/ consumo por demanda contratada',true,false,false,false,true),
	 (5258,'Venda de energia elétrica a não contribuinte',true,false,false,false,true),
	 (5301,'Prestação de serviço de comunicação p/ execução de serviço da mesma natureza',false,true,false,false,true),
	 (5302,'Prestação de serviço de comunicação a estabelecimento industrial',false,true,false,false,true) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (5303,'Prestação de serviço de comunicação a estabelecimento comercial',false,true,false,false,true),
	 (5304,'Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte',false,true,false,false,true),
	 (5305,'Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica',false,true,false,false,true),
	 (5306,'Prestação de serviço de comunicação a estabelecimento de produtor rural',false,true,false,false,true),
	 (5307,'Prestação de serviço de comunicação a não contribuinte',false,true,false,false,true),
	 (5351,'Prestação de serviço de transporte p/ execução de serviço da mesma natureza',false,false,true,false,true),
	 (5352,'Prestação de serviço de transporte a estabelecimento industrial',false,false,true,false,true),
	 (5353,'Prestação de serviço de transporte a estabelecimento comercial',false,false,true,false,true),
	 (5355,'Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica',false,false,true,false,true),
	 (5356,'Prestação de serviço de transporte a estabelecimento de produtor rural',false,false,true,false,true) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (5357,'Prestação de serviço de transporte a não contribuinte',false,false,true,false,true),
	 (5359,'Prestação de serviço de transporte a contribuinte ou a não-contribuinte, quando a mercadoria transportada esteja dispensada de emissão de Nota Fiscal  ',false,false,true,false,true),
	 (5401,'Venda de produção do estabelecimento quando o produto esteja sujeito a ST',true,false,false,false,true),
	 (5402,'Venda de produção do estabelecimento de produto sujeito a ST, em operação entre contribuintes substitutos do mesmo produto',true,false,false,false,true),
	 (5403,'Venda de mercadoria, adquirida ou recebida de terceiros, sujeita a ST, na condição de contribuinte-substituto',true,false,false,false,true),
	 (5405,'Venda de mercadoria, adquirida ou recebida de terceiros, sujeita a ST, na condição de contribuinte-substituído',true,false,false,false,true),
	 (5501,'Remessa de produção do estabelecimento, com fim específico de exportação',true,false,false,false,true),
	 (5502,'Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação',true,false,false,false,true),
	 (5651,'Venda de combustível ou lubrificante de produção do estabelecimento destinados à industrialização subseqüente',true,false,false,false,true),
	 (5652,'Venda de combustível ou lubrificante, de produção do estabelecimento, destinados à comercialização',true,false,false,false,true) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (5653,'Venda de combustível ou lubrificante, de produção do estabelecimento, destinados a consumidor ou usuário final',true,false,false,false,true),
	 (5654,'Venda de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados à industrialização subseqüente',true,false,false,false,true),
	 (5655,'Venda de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados à comercialização',true,false,false,false,true),
	 (5656,'Venda de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados a consumidor ou usuário final',true,false,false,false,true),
	 (5667,'Venda de combustível ou lubrificante a consumidor ou usuário final estabelecido em outra UF',true,false,false,false,true),
	 (5917,'Remessa de mercadoria em consignação mercantil ou industrial',true,false,false,false,true),
	 (5932,'Prestação de serviço de transporte iniciada em UF diversa daquela onde inscrito o prestador',true,false,true,false,true),
	 (5933,'Prestação de serviço tributado pelo Imposto Sobre Serviços de Qualquer Natureza',true,false,false,false,true),
	 (5949,'Outra saída de mercadoria ou prestação de serviço não especificado',true,false,false,false,true),
	 (6101,'Venda de produção do estabelecimento',true,false,false,false,true) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (6102,'Venda de mercadoria adquirida ou recebida de terceiros',true,false,false,false,true),
	 (6103,'Venda de produção do estabelecimento, efetuada fora do estabelecimento',true,false,false,false,true),
	 (6104,'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento',true,false,false,false,true),
	 (6105,'Venda de produção do estabelecimento que não deva por ele transitar',true,false,false,false,true),
	 (6106,'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar',true,false,false,false,true),
	 (6107,'Venda de produção do estabelecimento, destinada a não contribuinte',true,false,false,false,true),
	 (6108,'Venda de mercadoria adquirida ou recebida de terceiros, destinada a não contribuinte',true,false,false,false,true),
	 (6109,'Venda de produção do estabelecimento destinada à ZFM ou ALC',true,false,false,false,true),
	 (6110,'Venda de mercadoria, adquirida ou recebida de terceiros, destinada à ZFM ou ALC',true,false,false,false,true),
	 (6116,'Venda de produção do estabelecimento originada de encomenda p/ entrega futura',true,false,false,false,true) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (6117,'Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda p/ entrega futura',true,false,false,false,true),
	 (6118,'Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem',true,false,false,false,true),
	 (6119,'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem',true,false,false,false,true),
	 (6120,'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem',true,false,false,false,true),
	 (6122,'Venda de produção do estabelecimento remetida p/ industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente',true,false,false,false,true),
	 (6123,'Venda de mercadoria adquirida ou recebida de terceiros remetida p/ industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente',true,false,false,false,true),
	 (6124,'Industrialização efetuada p/ outra empresa',true,false,false,false,true),
	 (6125,'Industrialização efetuada p/ outra empresa quando a mercadoria recebida p/ utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria',true,false,false,false,true),
	 (6151,'Transferência de produção do estabelecimento',true,false,false,false,true),
	 (6152,'Transferência de mercadoria adquirida ou recebida de terceiros',true,false,false,false,true) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (6153,'Transferência de energia elétrica',true,false,false,false,true),
	 (6155,'Transferência de produção do estabelecimento, que não deva por ele transitar',true,false,false,false,true),
	 (6156,'Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar',true,false,false,false,true),
	 (6251,'Venda de energia elétrica p/ distribuição ou comercialização',true,false,false,false,true),
	 (6252,'Venda de energia elétrica p/ estabelecimento industrial',true,false,false,false,true),
	 (6253,'Venda de energia elétrica p/ estabelecimento comercial',true,false,false,false,true),
	 (6254,'Venda de energia elétrica p/ estabelecimento prestador de serviço de transporte',true,false,false,false,true),
	 (6255,'Venda de energia elétrica p/ estabelecimento prestador de serviço de comunicação',true,false,false,false,true),
	 (6256,'Venda de energia elétrica p/ estabelecimento de produtor rural',true,false,false,false,true),
	 (6257,'Venda de energia elétrica p/ consumo por demanda contratada',true,false,false,false,true) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (6258,'Venda de energia elétrica a não contribuinte',true,false,false,false,true),
	 (6301,'Prestação de serviço de comunicação p/ execução de serviço da mesma natureza',false,true,false,false,true),
	 (6302,'Prestação de serviço de comunicação a estabelecimento industrial',false,true,false,false,true),
	 (6303,'Prestação de serviço de comunicação a estabelecimento comercial',false,true,false,false,true),
	 (6304,'Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte',false,true,false,false,true),
	 (6305,'Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica',false,true,false,false,true),
	 (6306,'Prestação de serviço de comunicação a estabelecimento de produtor rural',false,true,false,false,true),
	 (6307,'Prestação de serviço de comunicação a não contribuinte',false,true,false,false,true),
	 (6351,'Prestação de serviço de transporte p/ execução de serviço da mesma natureza',false,false,true,false,true),
	 (6352,'Prestação de serviço de transporte a estabelecimento industrial',false,false,true,false,true) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (6353,'Prestação de serviço de transporte a estabelecimento comercial',false,false,true,false,true),
	 (6354,'Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação',false,false,true,false,true),
	 (6355,'Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica',false,false,true,false,true),
	 (6357,'Prestação de serviço de transporte a não contribuinte',false,false,true,false,true),
	 (6359,'Prestação de serviço de transporte a contribuinte ou a não-contribuinte, quando a mercadoria transportada esteja dispensada de emissão de Nota Fiscal  ',false,false,true,false,true),
	 (6360,'Prestação de serviço de transporte a contribuinte substituto em relação ao serviço de transporte  ',false,false,true,false,true),
	 (6401,'Venda de produção do estabelecimento quando o produto sujeito a ST',true,false,false,false,true),
	 (6402,'Venda de produção do estabelecimento de produto sujeito a ST, em operação entre contribuintes substitutos do mesmo produto',true,false,false,false,true),
	 (6403,'Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita a ST, na condição de contribuinte substituto',true,false,false,false,true),
	 (6404,'Venda de mercadoria sujeita a ST, cujo imposto já tenha sido retido anteriormente',true,false,false,false,true) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (6408,'Transferência de produção do estabelecimento quando o produto sujeito a ST',true,false,false,false,true),
	 (6409,'Transferência de mercadoria adquirida ou recebida de terceiros, sujeita a ST',true,false,false,false,true),
	 (6501,'Remessa de produção do estabelecimento, com fim específico de exportação',true,false,false,false,true),
	 (6502,'Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação',true,false,false,false,true),
	 (6651,'Venda de combustível ou lubrificante, de produção do estabelecimento, destinados à industrialização subseqüente',true,false,false,false,true),
	 (6652,'Venda de combustível ou lubrificante, de produção do estabelecimento, destinados à comercialização',true,false,false,false,true),
	 (6653,'Venda de combustível ou lubrificante, de produção do estabelecimento, destinados a consumidor ou usuário final ',true,false,false,false,true),
	 (6654,'Venda de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados à industrialização subseqüente ',true,false,false,false,true),
	 (6655,'Venda de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados à comercialização',true,false,false,false,true),
	 (6656,'Venda de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados a consumidor ou usuário final',true,false,false,false,true) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (6658,'Transferência de combustível ou lubrificante de produção do estabelecimento',true,false,false,false,true),
	 (6659,'Transferência de combustível ou lubrificante adquiridos ou recebidos de terceiros',true,false,false,false,true),
	 (6667,'Venda de combustível ou lubrificante a consumidor ou usuário final estabelecido em outra UF diferente da que ocorrer o consumo',true,false,false,false,true),
	 (6917,'Remessa de mercadoria em consignação mercantil ou industrial',true,false,false,false,true),
	 (6932,'Prestação de serviço de transporte iniciada em UF diversa daquela onde inscrito o prestador',true,false,true,false,true),
	 (6933,'Prestação de serviço tributado pelo Imposto Sobre Serviços de Qualquer Natureza ',true,false,false,false,true),
	 (6949,'Outra saída de mercadoria ou prestação de serviço não especificado',true,false,false,false,true),
	 (7101,'Venda de produção do estabelecimento',true,false,false,false,true),
	 (7102,'Venda de mercadoria adquirida ou recebida de terceiros',true,false,false,false,true),
	 (7105,'Venda de produção do estabelecimento, que não deva por ele transitar',true,false,false,false,true) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (7106,'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar',true,false,false,false,true),
	 (7127,'Venda de produção do estabelecimento sob o regime de drawback ',true,false,false,false,true),
	 (7251,'Venda de energia elétrica p/ o exterior',true,false,false,false,true),
	 (7301,'Prestação de serviço de comunicação p/ execução de serviço da mesma natureza',false,true,false,false,true),
	 (7358,'Prestação de serviço de transporte',false,false,true,false,true),
	 (7651,'Venda de combustível ou lubrificante de produção do estabelecimento',true,false,false,false,true),
	 (7654,'Venda de combustível ou lubrificante adquiridos ou recebidos de terceiros',true,false,false,false,true),
	 (7667,'Venda de combustível ou lubrificante a consumidor ou usuário final',true,false,false,false,true),
	 (7949,'Outra saída de mercadoria ou prestação de serviço não especificado',true,false,false,false,true),
	 (1101,'Compra p/ industrialização ou produção rural',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (1102,'Compra p/ comercialização',true,false,false,false,false),
	 (1111,'Compra p/ industrialização de mercadoria recebida anteriormente em consignação industrial',true,false,false,false,false),
	 (1113,'Compra p/ comercialização, de mercadoria recebida anteriormente em consignação mercantil',true,false,false,false,false),
	 (1116,'Compra p/ industrialização ou produção rural originada de encomenda p/ recebimento futuro',true,false,false,false,false),
	 (1117,'Compra p/ comercialização originada de encomenda p/ recebimento futuro',true,false,false,false,false),
	 (1118,'Compra de mercadoria p/ comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem.',true,false,false,false,false),
	 (1120,'Compra p/ industrialização, em venda à ordem, já recebida do vendedor remetente',true,false,false,false,false),
	 (1121,'Compra p/ comercialização, em venda à ordem, já recebida do vendedor remetente',true,false,false,false,false),
	 (1122,'Compra p/ industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente',true,false,false,false,false),
	 (1124,'Industrialização efetuada por outra empresa',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (1125,'Industrialização efetuada por outra empresa quando a mercadoria remetida p/ utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria',true,false,false,false,false),
	 (1126,'Compra p/ utilização na prestação de serviço sujeita ao ICMS',true,false,false,false,false),
	 (1128,'Compra p/ utilização na prestação de serviço sujeita ao ISSQN',true,false,false,false,false),
	 (1151,'Transferência p/ industrialização ou produção rural',true,false,false,false,false),
	 (1152,'Transferência p/ comercialização',true,false,false,false,false),
	 (1153,'Transferência de energia elétrica p/ distribuição',true,false,false,false,false),
	 (1154,'Transferência p/ utilização na prestação de serviço',true,false,false,false,false),
	 (1208,'Devolução de produção do estabelecimento, remetida em transferência',true,false,false,true,false),
	 (1209,'Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência',true,false,false,true,false),
	 (1212,'Devolução de venda no mercado interno de mercadoria industrializada e insumo importado sob o Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)',true,false,false,true,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (1251,'Compra de energia elétrica p/ distribuição ou comercialização',true,false,false,false,false),
	 (1252,'Compra de energia elétrica por estabelecimento industrial',true,false,false,false,false),
	 (1253,'Compra de energia elétrica por estabelecimento comercial',true,false,false,false,false),
	 (1254,'Compra de energia elétrica por estabelecimento prestador de serviço de transporte',true,false,false,false,false),
	 (1255,'Compra de energia elétrica por estabelecimento prestador de serviço de comunicação',true,false,false,false,false),
	 (1256,'Compra de energia elétrica por estabelecimento de produtor rural',true,false,false,false,false),
	 (1257,'Compra de energia elétrica p/ consumo por demanda contratada',true,false,false,false,false),
	 (1301,'Aquisição de serviço de comunicação p/ execução de serviço da mesma natureza',true,false,false,false,false),
	 (1302,'Aquisição de serviço de comunicação por estabelecimento industrial',true,false,false,false,false),
	 (1303,'Aquisição de serviço de comunicação por estabelecimento comercial',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (1304,'Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte',true,false,false,false,false),
	 (1305,'Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica',true,false,false,false,false),
	 (1306,'Aquisição de serviço de comunicação por estabelecimento de produtor rural',true,false,false,false,false),
	 (1351,'Aquisição de serviço de transporte p/ execução de serviço da mesma natureza',true,false,false,false,false),
	 (1352,'Aquisição de serviço de transporte por estabelecimento industrial',true,false,false,false,false),
	 (1353,'Aquisição de serviço de transporte por estabelecimento comercial',true,false,false,false,false),
	 (1354,'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação',true,false,false,false,false),
	 (1355,'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica',true,false,false,false,false),
	 (1356,'Aquisição de serviço de transporte por estabelecimento de produtor rural',true,false,false,false,false),
	 (1360,'Aquisição de serviço de transporte por contribuinte-substituto em relação ao serviço de transporte',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (1401,'Compra p/ industrialização ou produção rural de mercadoria sujeita a ST',true,false,false,false,false),
	 (1403,'Compra p/ comercialização em operação com mercadoria sujeita a ST',true,false,false,false,false),
	 (1406,'Compra de bem p/ o ativo imobilizado cuja mercadoria está sujeita a ST',true,false,false,false,false),
	 (1407,'Compra de mercadoria p/ uso ou consumo cuja mercadoria está sujeita a ST',true,false,false,false,false),
	 (1408,'Transferência p/ industrialização ou produção rural de mercadoria sujeita a ST',true,false,false,false,false),
	 (1409,'Transferência p/ comercialização em operação com mercadoria sujeita a ST',true,false,false,false,false),
	 (1414,'Retorno de mercadoria de produção do estabelecimento, remetida p/ venda fora do estabelecimento, sujeita a ST',true,false,false,false,false),
	 (1415,'Retorno de mercadoria adquirida ou recebida de terceiros, remetida p/ venda fora do estabelecimento em operação com mercadoria sujeita a ST',true,false,false,false,false),
	 (1451,'Retorno de animal do estabelecimento produtor',true,false,false,false,false),
	 (1452,'Retorno de insumo não utilizado na produção',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (1501,'Entrada de mercadoria recebida com fim específico de exportação',true,false,false,false,false),
	 (1505,'Entrada decorrente de devolução simbólica de mercadoria remetida p/ formação de lote de exportação, de produto industrializado ou produzido pelo próprio estabelecimento.',true,false,false,true,false),
	 (1506,'Entrada decorrente de devolução simbólica de mercadoria, adquirida ou recebida de terceiros, remetida p/ formação de lote de exportação.',true,false,false,true,false),
	 (1551,'Compra de bem p/ o ativo imobilizado',true,false,false,false,false),
	 (1552,'Transferência de bem do ativo imobilizado',true,false,false,false,false),
	 (1553,'Devolução de venda de bem do ativo imobilizado',true,false,false,true,false),
	 (1554,'Retorno de bem do ativo imobilizado remetido p/ uso fora do estabelecimento',true,false,false,false,false),
	 (1555,'Entrada de bem do ativo imobilizado de terceiro, remetido p/ uso no estabelecimento',true,false,false,false,false),
	 (1556,'Compra de material p/ uso ou consumo',true,false,false,false,false),
	 (1557,'Transferência de material p/ uso ou consumo',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (1601,'Recebimento, por transferência, de crédito de ICMS',true,false,false,false,false),
	 (1602,'Recebimento, por transferência, de saldo credor do ICMS, de outro estabelecimento da mesma empresa, p/ compensação de saldo devedor do imposto. ',true,false,false,false,false),
	 (1603,'Ressarcimento de ICMS retido por substituição tributária',true,false,false,false,false),
	 (1604,'Lançamento do crédito relativo à compra de bem p/ o ativo imobilizado',true,false,false,false,false),
	 (1605,'Recebimento, por transferência, de saldo devedor do ICMS de outro estabelecimento da mesma empresa',true,false,false,false,false),
	 (1651,'Compra de combustível ou lubrificante p/ industrialização subseqüente',true,false,false,false,false),
	 (1652,'Compra de combustível ou lubrificante p/ comercialização',true,false,false,false,false),
	 (1653,'Compra de combustível ou lubrificante por consumidor ou usuário final',true,false,false,false,false),
	 (1658,'Transferência de combustível ou lubrificante p/ industrialização',true,false,false,false,false),
	 (1659,'Transferência de combustível ou lubrificante p/ comercialização',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (1663,'Entrada de combustível ou lubrificante p/ armazenagem',true,false,false,false,false),
	 (1664,'Retorno de combustível ou lubrificante remetidos p/ armazenagem',true,false,false,false,false),
	 (1901,'Entrada p/ industrialização por encomenda',true,false,false,false,false),
	 (1902,'Retorno de mercadoria remetida p/ industrialização por encomenda',true,false,false,false,false),
	 (1903,'Entrada de mercadoria remetida p/ industrialização e não aplicada no referido processo',true,false,false,false,false),
	 (1904,'Retorno de remessa p/ venda fora do estabelecimento',true,false,false,false,false),
	 (1905,'Entrada de mercadoria recebida p/ depósito em depósito fechado ou armazém geral',true,false,false,false,false),
	 (1906,'Retorno de mercadoria remetida p/ depósito fechado ou armazém geral',true,false,false,false,false),
	 (1907,'Retorno simbólico de mercadoria remetida p/ depósito fechado ou armazém geral',true,false,false,false,false),
	 (1908,'Entrada de bem por conta de contrato de comodato',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (1909,'Retorno de bem remetido por conta de contrato de comodato',true,false,false,false,false),
	 (1910,'Entrada de bonificação, doação ou brinde',true,false,false,false,false),
	 (1912,'Entrada de mercadoria ou bem recebido p/ demonstração',true,false,false,false,false),
	 (1913,'Retorno de mercadoria ou bem remetido p/ demonstração',true,false,false,false,false),
	 (1914,'Retorno de mercadoria ou bem remetido p/ exposição ou feira',true,false,false,false,false),
	 (1915,'Entrada de mercadoria ou bem recebido p/ conserto ou reparo',true,false,false,false,false),
	 (1916,'Retorno de mercadoria ou bem remetido p/ conserto ou reparo',true,false,false,false,false),
	 (1917,'Entrada de mercadoria recebida em consignação mercantil ou industrial',true,false,false,false,false),
	 (1919,'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial',true,false,false,true,false),
	 (1920,'Entrada de vasilhame ou sacaria',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (1921,'Retorno de vasilhame ou sacaria',true,false,false,false,false),
	 (1922,'Lançamento efetuado a título de simples faturamento decorrente de compra p/ recebimento futuro',true,false,false,false,false),
	 (1923,'Entrada de mercadoria recebida do vendedor remetente, em venda à ordem',true,false,false,false,false),
	 (1924,'Entrada p/ industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente',true,false,false,false,false),
	 (1925,'Retorno de mercadoria remetida p/ industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente',true,false,false,false,false),
	 (1926,'Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação',true,false,false,false,false),
	 (1931,'Lançamento efetuado pelo tomador do serviço de transporte, quando a responsabilidade de retenção do imposto for atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não-inscrito na UF onde se tenha iniciado o serviço.',true,false,false,false,false),
	 (1932,'Aquisição de serviço de transporte iniciado em UF diversa daquela onde esteja inscrito o prestador',true,false,false,false,false),
	 (1933,'Aquisição de serviço tributado pelo Imposto sobre Serviços de Qualquer Natureza',true,false,false,false,false),
	 (1934,'Entrada simbólica de mercadoria recebida p/ depósito fechado ou armazém geral',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (1949,'Outra entrada de mercadoria ou prestação de serviço não especificada',true,false,false,false,false),
	 (2101,'Compra p/ industrialização ou produção rural',true,false,false,false,false),
	 (2102,'Compra p/ comercialização',true,false,false,false,false),
	 (2111,'Compra p/ industrialização de mercadoria recebida anteriormente em consignação industrial',true,false,false,false,false),
	 (2113,'Compra p/ comercialização, de mercadoria recebida anteriormente em consignação mercantil',true,false,false,false,false),
	 (2116,'Compra p/ industrialização ou produção rural originada de encomenda p/ recebimento futuro',true,false,false,false,false),
	 (2117,'Compra p/ comercialização originada de encomenda p/ recebimento futuro',true,false,false,false,false),
	 (2118,'Compra de mercadoria p/ comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem',true,false,false,false,false),
	 (2120,'Compra p/ industrialização, em venda à ordem, já recebida do vendedor remetente',true,false,false,false,false),
	 (2121,'Compra p/ comercialização, em venda à ordem, já recebida do vendedor remetente',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (2122,'Compra p/ industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente',true,false,false,false,false),
	 (2124,'Industrialização efetuada por outra empresa',true,false,false,false,false),
	 (2125,'Industrialização efetuada por outra empresa quando a mercadoria remetida p/ utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria',true,false,false,false,false),
	 (2126,'Compra p/ utilização na prestação de serviço sujeita ao ICMS',true,false,false,false,false),
	 (2128,'Compra p/ utilização na prestação de serviço sujeita ao ISSQN',true,false,false,false,false),
	 (2151,'Transferência p/ industrialização ou produção rural',true,false,false,false,false),
	 (2152,'Transferência p/ comercialização',true,false,false,false,false),
	 (2153,'Transferência de energia elétrica p/ distribuição',true,false,false,false,false),
	 (2154,'Transferência p/ utilização na prestação de serviço',true,false,false,false,false),
	 (2212,'Devolução de venda no mercado interno de mercadoria industrializada e insumo importado sob o Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)',true,false,false,true,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (2251,'Compra de energia elétrica p/ distribuição ou comercialização',true,false,false,false,false),
	 (2252,'Compra de energia elétrica por estabelecimento industrial',true,false,false,false,false),
	 (2253,'Compra de energia elétrica por estabelecimento comercial',true,false,false,false,false),
	 (2254,'Compra de energia elétrica por estabelecimento prestador de serviço de transporte',true,false,false,false,false),
	 (2255,'Compra de energia elétrica por estabelecimento prestador de serviço de comunicação',true,false,false,false,false),
	 (2256,'Compra de energia elétrica por estabelecimento de produtor rural',true,false,false,false,false),
	 (2257,'Compra de energia elétrica p/ consumo por demanda contratada',true,false,false,false,false),
	 (2301,'Aquisição de serviço de comunicação p/ execução de serviço da mesma natureza',true,false,false,false,false),
	 (2302,'Aquisição de serviço de comunicação por estabelecimento industrial',true,false,false,false,false),
	 (2303,'Aquisição de serviço de comunicação por estabelecimento comercial',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (2304,'Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte',true,false,false,false,false),
	 (2305,'Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica',true,false,false,false,false),
	 (2306,'Aquisição de serviço de comunicação por estabelecimento de produtor rural',true,false,false,false,false),
	 (2351,'Aquisição de serviço de transporte p/ execução de serviço da mesma natureza',true,false,false,false,false),
	 (2352,'Aquisição de serviço de transporte por estabelecimento industrial',true,false,false,false,false),
	 (2353,'Aquisição de serviço de transporte por estabelecimento comercial',true,false,false,false,false),
	 (2354,'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação',true,false,false,false,false),
	 (2355,'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica',true,false,false,false,false),
	 (2356,'Aquisição de serviço de transporte por estabelecimento de produtor rural',true,false,false,false,false),
	 (2401,'Compra p/ industrialização ou produção rural de mercadoria sujeita a ST',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (2403,'Compra p/ comercialização em operação com mercadoria sujeita a ST',true,false,false,false,false),
	 (2406,'Compra de bem p/ o ativo imobilizado cuja mercadoria está sujeita a ST',true,false,false,false,false),
	 (2407,'Compra de mercadoria p/ uso ou consumo cuja mercadoria está sujeita a ST',true,false,false,false,false),
	 (2408,'Transferência p/ industrialização ou produção rural de mercadoria sujeita a ST',true,false,false,false,false),
	 (2409,'Transferência p/ comercialização em operação com mercadoria sujeita a ST',true,false,false,false,false),
	 (2414,'Retorno de produção do estabelecimento, remetida p/ venda fora do estabelecimento, quando o produto sujeito a ST',true,false,false,false,false),
	 (2415,'Retorno de mercadoria adquirida ou recebida de terceiros, remetida p/ venda fora do estabelecimento em operação com mercadoria sujeita a ST',true,false,false,false,false),
	 (2501,'Entrada de mercadoria recebida com fim específico de exportação',true,false,false,false,false),
	 (2505,'Entrada decorrente de devolução simbólica de mercadoria remetida p/ formação de lote de exportação, de produto industrializado ou produzido pelo próprio estabelecimento.',true,false,false,true,false),
	 (2506,'Entrada decorrente de devolução simbólica de mercadoria, adquirida ou recebida de terceiros, remetida p/ formação de lote de exportação.',true,false,false,true,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (2551,'Compra de bem p/ o ativo imobilizado',true,false,false,false,false),
	 (2552,'Transferência de bem do ativo imobilizado',true,false,false,false,false),
	 (2553,'Devolução de venda de bem do ativo imobilizado',true,false,false,true,false),
	 (2554,'Retorno de bem do ativo imobilizado remetido p/ uso fora do estabelecimento',true,false,false,false,false),
	 (2555,'Entrada de bem do ativo imobilizado de terceiro, remetido p/ uso no estabelecimento',true,false,false,false,false),
	 (2556,'Compra de material p/ uso ou consumo',true,false,false,false,false),
	 (2557,'Transferência de material p/ uso ou consumo',true,false,false,false,false),
	 (2603,'Ressarcimento de ICMS retido por substituição tributária',true,false,false,false,false),
	 (2651,'Compra de combustível ou lubrificante p/ industrialização subseqüente',true,false,false,false,false),
	 (2652,'Compra de combustível ou lubrificante p/ comercialização',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (2653,'Compra de combustível ou lubrificante por consumidor ou usuário final',true,false,false,false,false),
	 (2658,'Transferência de combustível ou lubrificante p/ industrialização',true,false,false,false,false),
	 (2659,'Transferência de combustível ou lubrificante p/ comercialização ',true,false,false,false,false),
	 (2663,'Entrada de combustível ou lubrificante p/ armazenagem',true,false,false,false,false),
	 (2664,'Retorno de combustível ou lubrificante remetidos p/ armazenagem',true,false,false,false,false),
	 (2901,'Entrada p/ industrialização por encomenda',true,false,false,false,false),
	 (2902,'Retorno de mercadoria remetida p/ industrialização por encomenda',true,false,false,false,false),
	 (2903,'Entrada de mercadoria remetida p/ industrialização e não aplicada no referido processo',true,false,false,false,false),
	 (2904,'Retorno de remessa p/ venda fora do estabelecimento',true,false,false,false,false),
	 (2905,'Entrada de mercadoria recebida p/ depósito em depósito fechado ou armazém geral',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (2906,'Retorno de mercadoria remetida p/ depósito fechado ou armazém geral',true,false,false,false,false),
	 (2907,'Retorno simbólico de mercadoria remetida p/ depósito fechado ou armazém geral',true,false,false,false,false),
	 (2908,'Entrada de bem por conta de contrato de comodato',true,false,false,false,false),
	 (2909,'Retorno de bem remetido por conta de contrato de comodato',true,false,false,false,false),
	 (2910,'Entrada de bonificação, doação ou brinde',true,false,false,false,false),
	 (2911,'Entrada de amostra grátis',true,false,false,false,false),
	 (2912,'Entrada de mercadoria ou bem recebido p/ demonstração',true,false,false,false,false),
	 (2913,'Retorno de mercadoria ou bem remetido p/ demonstração',true,false,false,false,false),
	 (2914,'Retorno de mercadoria ou bem remetido p/ exposição ou feira',true,false,false,false,false),
	 (2915,'Entrada de mercadoria ou bem recebido p/ conserto ou reparo',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (2916,'Retorno de mercadoria ou bem remetido p/ conserto ou reparo',true,false,false,false,false),
	 (2917,'Entrada de mercadoria recebida em consignação mercantil ou industrial',true,false,false,false,false),
	 (2919,'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial',true,false,false,true,false),
	 (2920,'Entrada de vasilhame ou sacaria',true,false,false,false,false),
	 (2921,'Retorno de vasilhame ou sacaria',true,false,false,false,false),
	 (2922,'Lançamento efetuado a título de simples faturamento decorrente de compra p/ recebimento futuro',true,false,false,false,false),
	 (2923,'Entrada de mercadoria recebida do vendedor remetente, em venda à ordem',true,false,false,false,false),
	 (2924,'Entrada p/ industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente',true,false,false,false,false),
	 (2925,'Retorno de mercadoria remetida p/ industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente',true,false,false,false,false),
	 (2931,'Lançamento efetuado pelo tomador do serviço de transporte, quando a responsabilidade de retenção do imposto for atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não-inscrito na UF onde se tenha iniciado o serviço  ',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (2932,'Aquisição de serviço de transporte iniciado em UF diversa daquela onde esteja inscrito o prestador ',true,false,false,false,false),
	 (2933,'Aquisição de serviço tributado pelo Imposto Sobre Serviços de Qualquer Natureza',true,false,false,false,false),
	 (2934,'Entrada simbólica de mercadoria recebida p/ depósito fechado ou armazém geral',true,false,false,false,false),
	 (2949,'Outra entrada de mercadoria ou prestação de serviço não especificado',true,false,false,false,false),
	 (3101,'Compra p/ industrialização ou produção rural',true,false,false,false,false),
	 (3102,'Compra p/ comercialização',true,false,false,false,false),
	 (3126,'Compra p/ utilização na prestação de serviço sujeita ao ICMS',true,false,false,false,false),
	 (3127,'Compra p/ industrialização sob o regime de drawback ',true,false,false,false,false),
	 (3128,'Compra p/ utilização na prestação de serviço sujeita ao ISSQN',true,false,false,false,false),
	 (3129,'Compra para industrialização sob o Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (5658,'Transferência de combustível ou lubrificante de produção do estabelecimento',true,false,false,false,false),
	 (3212,'Devolução de venda no mercado externo de mercadoria industrializada sob o Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)',true,false,false,true,false),
	 (3251,'Compra de energia elétrica p/ distribuição ou comercialização',true,false,false,false,false),
	 (3301,'Aquisição de serviço de comunicação p/ execução de serviço da mesma natureza',true,false,false,false,false),
	 (3351,'Aquisição de serviço de transporte p/ execução de serviço da mesma natureza',true,false,false,false,false),
	 (3352,'Aquisição de serviço de transporte por estabelecimento industrial',true,false,false,false,false),
	 (3353,'Aquisição de serviço de transporte por estabelecimento comercial',true,false,false,false,false),
	 (3354,'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação',true,false,false,false,false),
	 (3355,'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica',true,false,false,false,false),
	 (3356,'Aquisição de serviço de transporte por estabelecimento de produtor rural',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (3551,'Compra de bem p/ o ativo imobilizado',true,false,false,false,false),
	 (3553,'Devolução de venda de bem do ativo imobilizado',true,false,false,true,false),
	 (3556,'Compra de material p/ uso ou consumo',true,false,false,false,false),
	 (3651,'Compra de combustível ou lubrificante p/ industrialização subseqüente',true,false,false,false,false),
	 (3652,'Compra de combustível ou lubrificante p/ comercialização',true,false,false,false,false),
	 (3653,'Compra de combustível ou lubrificante por consumidor ou usuário final',true,false,false,false,false),
	 (3930,'Lançamento efetuado a título de entrada de bem sob amparo de regime especial aduaneiro de admissão temporária',true,false,false,false,false),
	 (3949,'Outra entrada de mercadoria ou prestação de serviço não especificado',true,false,false,false,false),
	 (5111,'Venda de produção do estabelecimento remetida anteriormente em consignação industrial',true,false,false,false,false),
	 (5112,'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação industrial',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (5113,'Venda de produção do estabelecimento remetida anteriormente em consignação mercantil',true,false,false,false,false),
	 (5114,'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil',true,false,false,false,false),
	 (5115,'Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil',true,false,false,false,false),
	 (5129,'Venda de insumo importado e de mercadoria industrializada sob o amparo do Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)',true,false,false,false,false),
	 (5151,NULL,true,false,false,false,false),
	 (5152,'Transferência de mercadoria adquirida ou recebida de terceiros',true,false,false,false,false),
	 (5153,'Transferência de energia elétrica',true,false,false,false,false),
	 (5155,'Transferência de produção do estabelecimento, que não deva por ele transitar',true,false,false,false,false),
	 (5156,'Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar',true,false,false,false,false),
	 (5201,'Devolução de compra p/ industrialização ou produção rural',true,false,false,true,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (5202,'Devolução de compra p/ comercialização',true,false,false,true,false),
	 (5205,'Anulação de valor relativo a aquisição de serviço de comunicação',true,false,false,false,false),
	 (5206,'Anulação de valor relativo a aquisição de serviço de transporte',true,false,false,false,false),
	 (5207,'Anulação de valor relativo à compra de energia elétrica',true,false,false,false,false),
	 (5208,'Devolução de mercadoria recebida em transferência p/ industrialização ou produção rural ',true,false,false,true,false),
	 (5209,'Devolução de mercadoria recebida em transferência p/ comercialização',true,false,false,true,false),
	 (5210,'Devolução de compra p/ utilização na prestação de serviço',true,false,false,true,false),
	 (5360,'Prestação de serviço de transporte a contribuinte-substituto em relação ao serviço de transporte',false,false,true,false,false),
	 (5408,'Transferência de produção do estabelecimento quando o produto sujeito a ST',true,false,false,false,false),
	 (5409,'Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita a ST',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (5410,'Devolução de compra p/ industrialização de mercadoria sujeita a ST',true,false,false,true,false),
	 (5411,'Devolução de compra p/ comercialização em operação com mercadoria sujeita a ST',true,false,false,true,false),
	 (5412,'Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita a ST',true,false,false,true,false),
	 (5413,'Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita a ST.',true,false,false,true,false),
	 (5414,'Remessa de produção do estabelecimento p/ venda fora do estabelecimento, quando o produto sujeito a ST',true,false,false,false,false),
	 (5415,'Remessa de mercadoria adquirida ou recebida de terceiros p/ venda fora do estabelecimento, em operação com mercadoria sujeita a ST',true,false,false,false,false),
	 (5451,'Remessa de animal e de insumo p/ estabelecimento produtor',true,false,false,false,false),
	 (5503,'Devolução de mercadoria recebida com fim específico de exportação',true,false,false,true,false),
	 (5504,'Remessa de mercadoria p/ formação de lote de exportação, de produto industrializado ou produzido pelo próprio estabelecimento.',true,false,false,false,false),
	 (5505,'Remessa de mercadoria, adquirida ou recebida de terceiros, p/ formação de lote de exportação.',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (5551,'Venda de bem do ativo imobilizado',true,false,false,false,false),
	 (5552,'Transferência de bem do ativo imobilizado',true,false,false,false,false),
	 (5553,'Devolução de compra de bem p/ o ativo imobilizado',true,false,false,true,false),
	 (5554,'Remessa de bem do ativo imobilizado p/ uso fora do estabelecimento',true,false,false,false,false),
	 (5555,'Devolução de bem do ativo imobilizado de terceiro, recebido p/ uso no estabelecimento',true,false,false,true,false),
	 (5556,'Devolução de compra de material de uso ou consumo',true,false,false,true,false),
	 (5557,'Transferência de material de uso ou consumo',true,false,false,false,false),
	 (5601,'Transferência de crédito de ICMS acumulado',true,false,false,false,false),
	 (5602,'Transferência de saldo credor do ICMS, p/ outro estabelecimento da mesma empresa, destinado à compensação de saldo devedor do ICMS',true,false,false,false,false),
	 (5603,'Ressarcimento de ICMS retido por substituição tributária',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (5605,'Transferência de saldo devedor do ICMS de outro estabelecimento da mesma empresa  ',true,false,false,false,false),
	 (5606,'Utilização de saldo credor do ICMS p/ extinção por compensação de débitos fiscais',true,false,false,false,false),
	 (5657,'Remessa de combustível ou lubrificante, adquiridos ou recebidos de terceiros, p/ venda fora do estabelecimento',true,false,false,false,false),
	 (5659,'Transferência de combustível ou lubrificante adquiridos ou recebidos de terceiros',true,false,false,false,false),
	 (5660,'Devolução de compra de combustível ou lubrificante adquiridos p/ industrialização subseqüente',true,false,false,true,false),
	 (5661,'Devolução de compra de combustível ou lubrificante adquiridos p/ comercialização',true,false,false,true,false),
	 (5662,'Devolução de compra de combustível ou lubrificante adquiridos por consumidor ou usuário final',true,false,false,true,false),
	 (5663,'Remessa p/ armazenagem de combustível ou lubrificante',true,false,false,false,false),
	 (5664,'Retorno de combustível ou lubrificante recebidos p/ armazenagem',true,false,false,false,false),
	 (5665,'Retorno simbólico de combustível ou lubrificante recebidos p/ armazenagem',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (5666,'Remessa, por conta e ordem de terceiros, de combustível ou lubrificante recebidos p/ armazenagem',true,false,false,false,false),
	 (5901,'Remessa p/ industrialização por encomenda',true,false,false,false,false),
	 (5902,'Retorno de mercadoria utilizada na industrialização por encomenda',true,false,false,false,false),
	 (5903,'Retorno de mercadoria recebida p/ industrialização e não aplicada no referido processo',true,false,false,false,false),
	 (5904,'Remessa p/ venda fora do estabelecimento',true,false,false,false,false),
	 (5905,'Remessa p/ depósito fechado ou armazém geral',true,false,false,false,false),
	 (5906,'Retorno de mercadoria depositada em depósito fechado ou armazém geral',true,false,false,false,false),
	 (5907,'Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral',true,false,false,false,false),
	 (5908,'Remessa de bem por conta de contrato de comodato',true,false,false,false,false),
	 (5909,'Retorno de bem recebido por conta de contrato de comodato',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (5910,'Remessa em bonificação, doação ou brinde',true,false,false,false,false),
	 (5912,'Remessa de mercadoria ou bem p/ demonstração',true,false,false,false,false),
	 (5913,'Retorno de mercadoria ou bem recebido p/ demonstração',true,false,false,false,false),
	 (5914,'Remessa de mercadoria ou bem p/ exposição ou feira',true,false,false,false,false),
	 (5915,'Remessa de mercadoria ou bem p/ conserto ou reparo',true,false,false,false,false),
	 (5916,'Retorno de mercadoria ou bem recebido p/ conserto ou reparo',true,false,false,false,false),
	 (5918,'Devolução de mercadoria recebida em consignação mercantil ou industrial',true,false,false,true,false),
	 (5919,'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial',true,false,false,true,false),
	 (5920,'Remessa de vasilhame ou sacaria',true,false,false,false,false),
	 (5921,'Devolução de vasilhame ou sacaria',true,false,false,true,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (5922,'Lançamento efetuado a título de simples faturamento decorrente de venda p/ entrega futura',true,false,false,false,false),
	 (5923,'Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem ou em operações com armazém geral ou depósito fechado.',true,false,false,false,false),
	 (5924,'Remessa p/ industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente',true,false,false,false,false),
	 (5925,'Retorno de mercadoria recebida p/ industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente',true,false,false,false,false),
	 (5926,'Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação',true,false,false,false,false),
	 (5927,'Lançamento efetuado a título de baixa de estoque decorrente de perda, roubo ou deterioração',true,false,false,false,false),
	 (5928,'Lançamento efetuado a título de baixa de estoque decorrente do encerramento da atividade da empresa',true,false,false,false,false),
	 (5929,'Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal - ECF',true,false,false,false,false),
	 (5931,'Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na UF onde iniciado o serviço',true,false,true,false,false),
	 (5934,'Remessa simbólica de mercadoria depositada em armazém geral ou depósito fechado.',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (6111,'Venda de produção do estabelecimento remetida anteriormente em consignação industrial',true,false,false,false,false),
	 (6112,'Venda de mercadoria adquirida ou recebida de Terceiros remetida anteriormente em consignação industrial',true,false,false,false,false),
	 (6113,'Venda de produção do estabelecimento remetida anteriormente em consignação mercantil',true,false,false,false,false),
	 (6114,'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil',true,false,false,false,false),
	 (6115,'Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil',true,false,false,false,false),
	 (6129,'Venda de insumo importado e de mercadoria industrializada sob o amparo do Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)',true,false,false,false,false),
	 (6201,'Devolução de compra p/ industrialização ou produção rural',true,false,false,true,false),
	 (6202,'Devolução de compra p/ comercialização',true,false,false,true,false),
	 (6205,'Anulação de valor relativo a aquisição de serviço de comunicação',true,false,false,false,false),
	 (6206,'Anulação de valor relativo a aquisição de serviço de transporte',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (6207,'Anulação de valor relativo à compra de energia elétrica',true,false,false,false,false),
	 (6208,'Devolução de mercadoria recebida em transferência p/ industrialização ou produção rural ',true,false,false,true,false),
	 (6209,'Devolução de mercadoria recebida em transferência p/ comercialização',true,false,false,true,false),
	 (6210,'Devolução de compra p/ utilização na prestação de serviço',true,false,false,true,false),
	 (6410,'Devolução de compra p/ industrialização ou ptrodução rural quando a mercadoria sujeita a ST',true,false,false,true,false),
	 (6411,'Devolução de compra p/ comercialização em operação com mercadoria sujeita a ST',true,false,false,true,false),
	 (6412,'Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita a ST',true,false,false,true,false),
	 (6413,'Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita a ST',true,false,false,true,false),
	 (6414,'Remessa de produção do estabelecimento p/ venda fora do estabelecimento, quando o produto sujeito a ST',true,false,false,false,false),
	 (6415,'Remessa de mercadoria adquirida ou recebida de terceiros p/ venda fora do estabelecimento, quando a referida ração com mercadoria sujeita a ST',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (6503,'Devolução de mercadoria recebida com fim específico de exportação',true,false,false,true,false),
	 (6504,'Remessa de mercadoria p/ formação de lote de exportação, de produto industrializado ou produzido pelo próprio estabelecimento.',true,false,false,false,false),
	 (6505,'Remessa de mercadoria, adquirida ou recebida de terceiros, p/ formação de lote de exportação.',true,false,false,false,false),
	 (6551,'Venda de bem do ativo imobilizado',true,false,false,false,false),
	 (6552,'Transferência de bem do ativo imobilizado',true,false,false,false,false),
	 (6553,'Devolução de compra de bem p/ o ativo imobilizado',true,false,false,true,false),
	 (6554,'Remessa de bem do ativo imobilizado p/ uso fora do estabelecimento',true,false,false,false,false),
	 (6555,'Devolução de bem do ativo imobilizado de terceiro, recebido p/ uso no estabelecimento',true,false,false,true,false),
	 (6556,'Devolução de compra de material de uso ou consumo',true,false,false,true,false),
	 (6557,'Transferência de material de uso ou consumo',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (6603,'Ressarcimento de ICMS retido por substituição tributária',true,false,false,false,false),
	 (6657,'Remessa de combustível ou lubrificante, adquiridos ou recebidos de terceiros, p/ venda fora do estabelecimento',true,false,false,false,false),
	 (6660,'Devolução de compra de combustível ou lubrificante adquiridos p/ industrialização subseqüente',true,false,false,true,false),
	 (6661,'Devolução de compra de combustível ou lubrificante adquiridos p/ comercialização',true,false,false,true,false),
	 (6662,'Devolução de compra de combustível ou lubrificante adquiridos por consumidor ou usuário final',true,false,false,true,false),
	 (6663,'Remessa p/ armazenagem de combustível ou lubrificante',true,false,false,false,false),
	 (6664,'Retorno de combustível ou lubrificante recebidos p/ armazenagem',true,false,false,false,false),
	 (6665,'Retorno simbólico de combustível ou lubrificante recebidos p/ armazenagem',true,false,false,false,false),
	 (6666,'Remessa, por conta e ordem de terceiros, de combustível ou lubrificante recebidos p/ armazenagem',true,false,false,false,false),
	 (6901,'Remessa p/ industrialização por encomenda',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (6902,'Retorno de mercadoria utilizada na industrialização por encomenda',true,false,false,false,false),
	 (6903,'Retorno de mercadoria recebida p/ industrialização e não aplicada no referido processo',true,false,false,false,false),
	 (6904,'Remessa p/ venda fora do estabelecimento',true,false,false,false,false),
	 (6905,'Remessa p/ depósito fechado ou armazém geral',true,false,false,false,false),
	 (6906,'Retorno de mercadoria depositada em depósito fechado ou armazém geral',true,false,false,false,false),
	 (6907,'Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral',true,false,false,false,false),
	 (6908,'Remessa de bem por conta de contrato de comodato',true,false,false,false,false),
	 (6909,'Retorno de bem recebido por conta de contrato de comodato',true,false,false,false,false),
	 (6910,'Remessa em bonificação, doação ou brinde',true,false,false,false,false),
	 (6911,'Remessa de amostra grátis',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (6912,'Remessa de mercadoria ou bem p/ demonstração',true,false,false,false,false),
	 (6913,'Retorno de mercadoria ou bem recebido p/ demonstração',true,false,false,false,false),
	 (6914,'Remessa de mercadoria ou bem p/ exposição ou feira',true,false,false,false,false),
	 (6915,'Remessa de mercadoria ou bem p/ conserto ou reparo',true,false,false,false,false),
	 (6916,'Retorno de mercadoria ou bem recebido p/ conserto ou reparo',true,false,false,false,false),
	 (6918,'Devolução de mercadoria recebida em consignação mercantil ou industrial',true,false,false,true,false),
	 (6919,'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial',true,false,false,true,false),
	 (6920,'Remessa de vasilhame ou sacaria',true,false,false,false,false),
	 (6921,'Devolução de vasilhame ou sacaria',true,false,false,true,false),
	 (6922,'Lançamento efetuado a título de simples faturamento decorrente de venda p/ entrega futura',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (6923,'Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem ou em operações com armazém geral ou depósito fechado',true,false,false,false,false),
	 (6924,'Remessa p/ industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente',true,false,false,false,false),
	 (6925,'Retorno de mercadoria recebida p/ industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente',true,false,false,false,false),
	 (6929,'Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal - ECF',true,false,false,false,false),
	 (6931,'Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na UF onde iniciado o serviço',true,false,true,false,false),
	 (6934,'Remessa simbólica de mercadoria depositada em armazém geral ou depósito fechado',true,false,false,false,false),
	 (7129,'Venda de produção do estabelecimento ao mercado externo de mercadoria industrializada sob o amparo do Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)',true,false,false,false,false),
	 (7201,'Devolução de compra p/ industrialização ou produção rural',true,false,false,true,false),
	 (7202,'Devolução de compra p/ comercialização',true,false,false,true,false),
	 (7205,'Anulação de valor relativo à aquisição de serviço de comunicação',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (7206,'Anulação de valor relativo a aquisição de serviço de transporte',true,false,false,false,false),
	 (7207,'Anulação de valor relativo à compra de energia elétrica',true,false,false,false,false),
	 (7210,'Devolução de compra p/ utilização na prestação de serviço',true,false,false,true,false),
	 (7211,'Devolução de compras p/ industrialização sob o regime de drawback ',true,false,false,true,false),
	 (7212,'Devolução de compras para industrialização sob o regime de Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)',true,false,false,true,false),
	 (7501,'Exportação de mercadorias recebidas com fim específico de exportação',true,false,false,false,false),
	 (7551,'Venda de bem do ativo imobilizado',true,false,false,false,false),
	 (7553,'Devolução de compra de bem p/ o ativo imobilizado',true,false,false,true,false),
	 (7556,'Devolução de compra de material de uso ou consumo',true,false,false,true,false),
	 (7930,'Lançamento efetuado a título de devolução de bem cuja entrada tenha ocorrido sob amparo de regime especial aduaneiro de admissão temporária',true,false,false,false,false) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (1159,'Entrada decorrente do fornecimento de produto ou mercadoria de ato cooperativo',false,false,false,false,NULL),
	 (1453,'Retorno do animal ou da produção - Sistema de Integração e Parceria Rural',false,false,false,false,NULL),
	 (1454,'Retorno simbólico do animal ou da produção - Sistema de Integração e Parceria Rural',false,false,false,false,NULL),
	 (1455,'Retorno de insumo não utilizado na produção - Sistema de Integração e Parceria Rural',false,false,false,false,NULL),
	 (1456,'Entrada referente a remuneração do produtor no Sistema de Integração e Parceria Rural',false,false,false,false,NULL),
	 (1657,'Retorno de remessa de combustível ou lubrificante para venda fora do estabelecimento',false,false,false,false,NULL),
	 (2159,'Entrada decorrente do fornecimento de produto ou mercadoria de ato cooperativo',false,false,false,false,NULL),
	 (2451,'Entrada de animal - Sistema de Integração e Parceria Rural',false,false,false,false,NULL),
	 (2452,'Entrada de insumo - Sistema de Integração e Parceria Rural',false,false,false,false,NULL),
	 (2453,'Retorno do animal ou da produção - Sistema de Integração e Parceria Rural',false,false,false,false,NULL) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (2454,'Retorno simbólico do animal ou da produção - Sistema de Integração e Parceria Rural',false,false,false,false,NULL),
	 (2455,'Retorno de insumo não utilizado na produção - Sistema de Integração e Parceria Rural',false,false,false,false,NULL),
	 (2456,'Entrada referente a remuneração do produtor no Sistema de Integração e Parceria Rural',false,false,false,false,NULL),
	 (2657,'Retorno de remessa de combustível ou lubrificante para venda fora do estabelecimento',false,false,false,false,NULL),
	 (5159,'Fornecimento de produção do estabelecimento de ato cooperativo',false,false,false,false,NULL),
	 (5160,'Fornecimento de mercadoria adquirida ou recebida de terceiros de ato cooperativo',false,false,false,false,NULL),
	 (5452,'Remessa de insumo - Sistema de Integração e Parceria Rural',false,false,false,false,NULL),
	 (5453,'Retorno de animal ou da produção - Sistema de Integração e Parceria Rural',false,false,false,false,NULL),
	 (5454,'Retorno simbólico de animal ou da produção - Sistema de Integração e Parceria Rural',false,false,false,false,NULL),
	 (5455,'Retorno de insumos não utilizados na produção - Sistema de Integração e Parceria Rural',false,false,false,false,NULL) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (5456,'Saída referente a remuneração do produtor - Sistema de Integração e Parceria Rural',false,false,false,false,NULL),
	 (6159,'Fornecimento de produção do estabelecimento de ato cooperativo',false,false,false,false,NULL),
	 (6160,'Fornecimento de mercadoria adquirida ou recebida de terceiros de ato cooperativo',false,false,false,false,NULL),
	 (6451,'Remessa de animal - Sistema de Integração e Parceria Rural',false,false,false,false,NULL),
	 (6452,'Remessa de insumo - Sistema de Integração e Parceria Rural',false,false,false,false,NULL),
	 (6453,'Retorno de animal ou da produção - Sistema de Integração e Parceria Rural',false,false,false,false,NULL),
	 (6454,'Retorno simbólico de animal ou da produção - Sistema de Integração e Parceria Rural',false,false,false,false,NULL),
	 (6455,'Retorno de insumos não utilizados na produção - Sistema de Integração e Parceria Rural',false,false,false,false,NULL),
	 (6456,'Saída referente a remuneração do produtor - Sistema de Integração e Parceria Rural',false,false,false,false,NULL),
	 (7504,'Exportação de mercadoria que foi objeto de formação de lote de exportação',false,false,false,false,NULL) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (1131,'Entrada de mercadoria com previsão de posterior ajuste ou fixação de preço, decorrente de operação de ato cooperativo.',false,false,false,false,NULL),
	 (1132,'Fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para comercialização',false,false,false,false,NULL),
	 (1135,'Fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para industrialização.',false,false,false,false,NULL),
	 (1213,'Devolução de remessa de produção do estabelecimento com previsão de posterior ajuste ou fixação de preço, em ato cooperativo.',false,false,false,false,NULL),
	 (1214,'Devolução de fixação de preço de produção do estabelecimento produtor, de ato cooperativo.',false,false,false,false,NULL),
	 (2131,'Entrada de mercadoria com previsão de posterior ajuste ou fixação de preço, decorrente de operação de ato cooperativo.',false,false,false,false,NULL),
	 (2132,'Fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para comercialização.',false,false,false,false,NULL),
	 (2135,'Fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para industrialização.',false,false,false,false,NULL),
	 (2213,'Devolução de remessa de produção do estabelecimento com previsão de posterior ajuste ou fixação de preço, em ato cooperativo.',false,false,false,false,NULL),
	 (2214,'Devolução de fixação de preço de produção do estabelecimento produtor, de ato cooperativo.',false,false,false,false,NULL) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (5131,'Remessa de produção do estabelecimento, com previsão de posterior ajuste ou fixação de preço, de ato cooperativo.',false,false,false,false,NULL),
	 (5132,'Fixação de preço de produção do estabelecimento, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço de ato cooperativo.',false,false,false,false,NULL),
	 (5213,'Devolução de entrada de mercadoria com previsão de posterior ajuste ou fixação de preço, em ato cooperativo.',false,false,false,false,NULL),
	 (5214,'Devolução de fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, de ato cooperativo, para comercialização.',false,false,false,false,NULL),
	 (5215,'Devolução de fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, de ato cooperativo, para industrialização.',false,false,false,false,NULL),
	 (6131,'Remessa de produção de estabelecimento, com previsão de posterior ajuste ou fixação de preço de ato cooperativo.',false,false,false,false,NULL),
	 (6132,'Fixação de preço de produção do estabelecimento, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço ou fixação de preço de ato cooperativo.',false,false,false,false,NULL),
	 (6213,'Devolução de entrada de mercadoria com previsão de posterior ajuste ou fixação de preço, em ato cooperativo.',false,false,false,false,NULL),
	 (6214,'Devolução de fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, de ato cooperativo, para comercialização.',false,false,false,false,NULL),
	 (6215,'Devolução de fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, de ato cooperativo para industrialização.',false,false,false,false,NULL) ON CONFLICT DO NOTHING;
INSERT INTO cfop (codigo,descricao,nfe,comunica,transp,devol,rba) VALUES
	 (1215,'Devolução de fornecimento de produção do estabelecimento de ato cooperativo',false,false,false,false,NULL),
	 (1216,'Devolução de fornecimento de mercadoria adquirida ou recebida de terceiros de ato cooperativo',false,false,false,false,NULL),
	 (2215,'Devolução de fornecimento de produção do estabelecimento de ato cooperativo',false,false,false,false,NULL),
	 (2216,'Devolução de fornecimento de mercadoria adquirida ou recebida de terceiros de ato cooperativo',false,false,false,false,NULL),
	 (5216,'Devolução de entrada decorrente do fornecimento de produto ou mercadoria de ato cooperativo',false,false,false,false,NULL),
	 (6216,'Devolução de entrada decorrente do fornecimento de produto ou mercadoria de ato cooperativo',false,false,false,false,NULL),
	 (3552,'Entrada de produtos destinados ao uso ou consumo de bordo, em embarcações ou aeronaves exclusivamente em tráfego internacional com destino ao exterior',false,false,false,false,NULL),
	 (3667,'Entrada de combustível ou lubrificante para consumo final, em embarcações ou aeronaves exclusivamente em tráfego internacional com destino ao exterior',false,false,false,false,NULL),
	 (7552,'Saída de produtos destinados ao uso ou consumo de bordo, em embarcações ou aeronaves exclusivamente em tráfego internacional com destino ao exterior',false,false,false,false,NULL) ON CONFLICT DO NOTHING;